# Generated by Django 5.2.7 on 2025-10-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20, unique=True)),
                ('emp_mail', models.EmailField(max_length=30)),
                ('emp_pic', models.FileField(upload_to='media')),
            ],
        ),
    ]
